config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   root 'accounts#index'
   get 'dashboard' =>'accounts#dashboard'

   resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base

	belongs_to :user
	def self.dashboard(current_user)
		data=Account.select("title,sum(expense) as total").where(user: current_user).group("title")
		data.map{|d|[d.title,d.total]}
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :accounts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def index
		@accounts=Account.where(user: current_user).last(5)
	end

	def new
		@account = Account.new
	end


	def create
		@account = Account.new(account_params)
		@account.user = current_user
		if @account.save
			redirect_to root_path
		else
			render  :new
		end
	end

	def destroy
		@account=Account.find(params[:id])
		@account.destroy
		redirect_to root_path
	end

	def dashboard
		@data=Account.dashboard(current_user)
	end

	private
	def  account_params
	params.require(:account).permit(:title,:expense,:datetime)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 before_action :configure_permitted_parameters, if: :devise_controller?

  	protected

  	def configure_permitted_parameters
   	 devise_parameter_sanitizer.for(:sign_up) << :username
  	end
  	
  	include Pundit
  	protect_from_forgery
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/dashboard.html.erb
<h2>Dashboard</h2>

<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
<script type="text/javascript"  src="http://code.highcharts.com/highcharts.js"></script>
<script type= "text/javascript">

$(function () {

    $('#container').highcharts({

        chart: {

            plotBackgroundColor: null,

            plotBorderWidth: null,

            plotShadow: false

        },

        title: {

            text: 'Pie chart - For your own expense account'

        },

        tooltip: {

            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'

        },

        plotOptions: {

            pie: {

                allowPointSelect: true,

                cursor: 'pointer',

                dataLabels: {

                    enabled: true,

                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',

                    style: {

                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'

                    }

                }

            }

        },

        series: [{

            type: 'pie',

            name: 'Browser share',

            data: <%= @data.to_json.html_safe%>

        }]

    });

});





</script>

app/views/accounts/index.html.erb
<h2>Account APP</h2>
<br>
	<% if user_signed_in? %>
	<%=current_user.username%>你好	
	<%= link_to "新增帳目", new_account_path %>
	<% @accounts.each do |account|%>
	
	<h4>項目: <%= account.title%> ;花費金額: $<%= account.expense%>
	<%= link_to "刪除此紀錄", account_path(account),method:"delete"  %>
	</h4> 
	<% end %>
	<% else %>
	立即<%= link_to "登入", new_user_session_path %>，從現在開始記錄你每天的花費
	




<% end %>

app/views/accounts/new.html.erb
<h2>新增帳目</h2>

<%= form_for  @account do |f|%>
<div>

	項目
	<%= f.select :title, options_for_select(["請選擇", "home", "personal", "food", "car", "shopping"],:disabled => ["請選擇"]) %>
</div>
<div>
	花費金額
	<%=f.text_field :expense %>
</div>
<div>
	<%=f.hidden_field :datetime %>
</div>

<%=f.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accounting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	
	<%= link_to "回首頁", root_path%>
	<% if user_signed_in? %>
	<%=current_user.username%>你好	
	<%= link_to "登出", destroy_user_session_path,method:'delete' %>
	<% else %>
	<%= link_to "註冊", new_user_registration_path %>
	<%= link_to "登入", new_user_session_path %>
	<% end %>
	<%= link_to "dashboard", dashboard_path %>

</header>

<%= yield %>

</body>
</html>